Tabernicola\JukeCloudBundle\Entity\Song:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [title, artist, disk]
            message: 'Esta canción ya existe en la libreria'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [path]
            message: 'Ya existe una referencia a esta canción en la libreria'
            groups: [extern]
    properties:
        file:
            - File:
                maxSize: 15M
                mimeTypesMessage: El archivo seleccionado no ha podido ser reconocido como archivo de audio/vídeo
                groups: [local]
        title:
            - NotBlank: ~
        disk:
            - NotNull: ~
        artist:
            - NotNull: ~
        number:
            - Range:
                min: 1
                max: 999